# Generated by Django 3.0.7 on 2020-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원목록'},
        ),
        migrations.AddField(
            model_name='member',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
